language: go
sudo: false
env:
  matrix:
    - GO111MODULE=on
matrix:
  include:
    - os: linux
      go: 1.12.x
      cache:
        directories:
          - "/home/travis/.cache/go-build"
    - os: osx
      go: 1.12.x
      cache:
        directories:
          - "/Users/travis/Library/Caches/go-build"
before_install:
- go get -u github.com/client9/misspell/cmd/misspell
- go get -u golang.org/x/lint/golint
- go get -u honnef.co/go/tools/cmd/staticcheck
- go get github.com/fzipp/gocyclo
- go get golang.org/x/tools/cmd/cover
# Install gcc, from https://travis-ci.community/t/go-cant-find-gcc-with-go1-11-1-on-windows/293/5
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y mingw; export PATH=/c/tools/mingw64/bin:"$PATH"; fi
before_script:
- GOFILES=$(find . -type f -name '*.go' | grep -v vendor)
script:
# Just check gofmt on linux, it's the fastest builder
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -z $(gofmt -s -l $GOFILES); fi
- go test ./... -race -coverprofile=coverage.txt -covermode=atomic
- misspell -error -locale US $GOFILES
- gocyclo -over 50 $GOFILES
- golint -set_exit_status $GOFILES
- staticcheck ./...
after_success:
- bash <(curl -s https://codecov.io/bash)
