language: go
sudo: false
os:
- linux
- osx
go:
- 1.11
osx_image: xcode9.1
before_install:
- go get github.com/mattn/goveralls
- go get -u github.com/client9/misspell/cmd/misspell
- go get -u golang.org/x/lint/golint
# fzipp/gocyclo hasn't updated master in years, we may want to consider not using it
- go get github.com/fzipp/gocyclo
before_script:
- GOFILES=$(find . -type f -name '*.go' | grep -v vendor)
script:
- test -z $(gofmt -s -l $GOFILES)
- go test ./...
- misspell -error -locale US $GOFILES
# over 46 for reader.parseLine
gocyclo -over 46 $GOFILES
- golint -set_exit_status $GOFILES
after_success:
- goveralls -repotoken $COVERALLS_TOKEN